/**
 * DocumentPlan — the hierarchical report index generated by the Architect.
 *
 * Structure:
 *   DocumentPlan
 *     └─ MacroSection[]     (e.g. "1. Analisi di Mercato")
 *          └─ SubChapter[]  (e.g. "1.1 Trend", "1.2 Regolamentazioni")
 *
 * The Architect (Tier 2 reasoning model) produces this JSON.
 * The Ghostwriter (Tier 3) iterates it chapter by chapter.
 */
import { z } from 'zod';
import { extractJson } from './extract-json';

// ── Focus area enum (mirrors ModuleId — Zod enum for runtime safety) ─────────
export const FocusAreaSchema = z.enum([
  'market_dynamics',
  'competitor_intelligence',
  'product_tech',
  'economics_pricing',
  'marketing_angles',   // tier 2+ (reserved)
  'corporate_health',   // tier 3+ (reserved)
]);
export type FocusArea = z.infer<typeof FocusAreaSchema>;

// ── SubChapter ────────────────────────────────────────────────────────────────
export const SubChapterSchema = z.object({
  sub_id: z.string(),
  /** Hierarchical number, e.g. "1.1", "2.3" */
  sub_number: z.string(),
  title: z.string(),
  /** Minimum 400, maximum 2000 — Architect decides based on importance */
  target_words: z.number().min(400).max(2000),
  /** Which ledger modules contain relevant data for this sub-chapter */
  required_data_focus: z.array(FocusAreaSchema).min(1),
  /** Copy-specific directives adapted to the target_audience */
  ghostwriter_instructions: z.string(),
  /** Metrics/data points that MUST appear inline (e.g. "TAM_italia_2025", "CAC_medio_settore") */
  must_include_metrics: z.array(z.string()),
});
export type SubChapter = z.infer<typeof SubChapterSchema>;

// ── MacroSection ──────────────────────────────────────────────────────────────
export const MacroSectionSchema = z.object({
  section_id: z.string(),
  /** 1-based integer */
  section_number: z.number().int().min(1),
  /** Full title including number, e.g. "1. Analisi di Mercato e Trend" */
  section_title: z.string(),
  sub_chapters: z.array(SubChapterSchema).min(1),
});
export type MacroSection = z.infer<typeof MacroSectionSchema>;

// ── DocumentPlan ──────────────────────────────────────────────────────────────
export const DocumentPlanSchema = z.object({
  macro_sections: z.array(MacroSectionSchema).min(1),
});
export type DocumentPlan = z.infer<typeof DocumentPlanSchema>;

// ── Validation helper ─────────────────────────────────────────────────────────
export function parseDocumentPlan(rawText: string): {
  data: DocumentPlan | null;
  error: string | null;
} {
  try {
    const jsonStr = extractJson(rawText);
    const parsed = JSON.parse(jsonStr) as unknown;
    const result = DocumentPlanSchema.safeParse(parsed);
    if (result.success) return { data: result.data, error: null };
    const issues = result.error.issues.slice(0, 5).map((i) => `${i.path.join('.')}: ${i.message}`).join('; ');
    return { data: null, error: `Zod: ${issues}` };
  } catch (err) {
    return { data: null, error: err instanceof Error ? err.message : 'parse error' };
  }
}

// ── Static fallback plans (used when Architect LLM fails) ─────────────────────
export function buildDefaultPlan(effort_tier: 1 | 2 | 3 | 4): DocumentPlan {
  const plans: Record<number, DocumentPlan> = {
    1: {
      macro_sections: [
        {
          section_id: 's1', section_number: 1, section_title: '1. Contesto di Mercato',
          sub_chapters: [
            { sub_id: '1.1', sub_number: '1.1', title: 'Dimensioni e Trend del Mercato', target_words: 600, required_data_focus: ['market_dynamics'], ghostwriter_instructions: 'Cita TAM e CAGR con fonte. Max 4 righe per paragrafo.', must_include_metrics: ['TAM_italia', 'CAGR'] },
            { sub_id: '1.2', sub_number: '1.2', title: 'Barriere e Regolamentazioni', target_words: 500, required_data_focus: ['market_dynamics'], ghostwriter_instructions: 'Elenca le barriere normative con impatto pratico.', must_include_metrics: [] },
            { sub_id: '1.3', sub_number: '1.3', title: 'Trend Tecnologici', target_words: 500, required_data_focus: ['product_tech', 'market_dynamics'], ghostwriter_instructions: 'Solo trend con adozione misurabile nel settore.', must_include_metrics: [] },
          ],
        },
        {
          section_id: 's2', section_number: 2, section_title: '2. Analisi della Concorrenza',
          sub_chapters: [
            { sub_id: '2.1', sub_number: '2.1', title: 'Mappa dei Competitor', target_words: 700, required_data_focus: ['competitor_intelligence'], ghostwriter_instructions: 'Tabella con nome, prezzi, punti deboli verificati da recensioni.', must_include_metrics: ['prezzo_range', 'review_score'] },
            { sub_id: '2.2', sub_number: '2.2', title: 'Vulnerabilità dei Leader', target_words: 600, required_data_focus: ['competitor_intelligence'], ghostwriter_instructions: 'Cita virgolettati reali da recensioni negative. Sii brutale.', must_include_metrics: [] },
            { sub_id: '2.3', sub_number: '2.3', title: 'Posizionamento e Gap', target_words: 500, required_data_focus: ['competitor_intelligence', 'product_tech'], ghostwriter_instructions: 'Identifica il gap di posizionamento non coperto da nessun competitor.', must_include_metrics: [] },
          ],
        },
        {
          section_id: 's3', section_number: 3, section_title: '3. Economia del Settore',
          sub_chapters: [
            { sub_id: '3.1', sub_number: '3.1', title: 'Struttura dei Prezzi', target_words: 600, required_data_focus: ['economics_pricing'], ghostwriter_instructions: 'Prezzi in euro, non "premium" o "accessibile". Cita listini reali.', must_include_metrics: ['prezzo_medio', 'margine_lordo'] },
            { sub_id: '3.2', sub_number: '3.2', title: 'KPI Economici di Settore', target_words: 500, required_data_focus: ['economics_pricing'], ghostwriter_instructions: 'LTV, CAC, churn benchmark. Con fonte.', must_include_metrics: ['LTV', 'CAC', 'churn'] },
            { sub_id: '3.3', sub_number: '3.3', title: 'Costo di Switching', target_words: 400, required_data_focus: ['economics_pricing'], ghostwriter_instructions: 'Stima in settimane e euro per cambiare fornitore.', must_include_metrics: [] },
          ],
        },
        {
          section_id: 's4', section_number: 4, section_title: '4. Strategia e Raccomandazioni',
          sub_chapters: [
            { sub_id: '4.1', sub_number: '4.1', title: 'Segmenti Prioritari', target_words: 600, required_data_focus: ['market_dynamics', 'competitor_intelligence'], ghostwriter_instructions: 'Max 3 segmenti con criteri di scelta quantificati.', must_include_metrics: [] },
            { sub_id: '4.2', sub_number: '4.2', title: 'Leve Competitive', target_words: 600, required_data_focus: ['product_tech', 'competitor_intelligence'], ghostwriter_instructions: 'Cosa fare nei prossimi 30 giorni. Azione concreta, non teoria.', must_include_metrics: [] },
            { sub_id: '4.3', sub_number: '4.3', title: 'Rischi Principali', target_words: 500, required_data_focus: ['market_dynamics', 'economics_pricing'], ghostwriter_instructions: 'Top 3 rischi con probabilità e impatto. Niente ottimismo.', must_include_metrics: [] },
          ],
        },
      ],
    },
  };

  // Tier 2-4: use tier 1 as base and add placeholder sections
  // (in production, the Architect LLM generates the full plan dynamically)
  const basePlan = plans[1];
  if (effort_tier === 1) return basePlan;

  // For tier 2+, clone base and append additional sections as placeholders
  return {
    macro_sections: [
      ...basePlan.macro_sections,
      ...(effort_tier >= 2 ? [{
        section_id: 's5', section_number: 5, section_title: '5. Canali e Copy Commerciale',
        sub_chapters: [
          { sub_id: '5.1', sub_number: '5.1', title: 'Messaggi per Segmento', target_words: 700, required_data_focus: ['competitor_intelligence' as FocusArea, 'market_dynamics' as FocusArea], ghostwriter_instructions: 'Un messaggio per segmento. Headline + proof point + call to action.', must_include_metrics: [] },
          { sub_id: '5.2', sub_number: '5.2', title: 'Obiezioni e Contrattacchi', target_words: 600, required_data_focus: ['competitor_intelligence' as FocusArea], ghostwriter_instructions: 'Top 5 obiezioni con risposta pronta. Stile script commerciale.', must_include_metrics: [] },
        ],
      }] : []),
      ...(effort_tier >= 3 ? [{
        section_id: 's6', section_number: 6, section_title: '6. Road Map Operativa',
        sub_chapters: [
          { sub_id: '6.1', sub_number: '6.1', title: 'Priorità 30 Giorni', target_words: 600, required_data_focus: ['market_dynamics' as FocusArea, 'economics_pricing' as FocusArea], ghostwriter_instructions: '5 azioni concrete, responsabile, KPI di verifica.', must_include_metrics: [] },
          { sub_id: '6.2', sub_number: '6.2', title: 'Test e Esperimenti', target_words: 500, required_data_focus: ['market_dynamics' as FocusArea], ghostwriter_instructions: 'Test con ICE score. Budget minimo per validare.', must_include_metrics: [] },
        ],
      }] : []),
    ],
  };
}
